
name: Build and deploy API to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies and run tests
        run: npm install
        working-directory: ./server

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: ./server

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: flavorverse-api
          path: server/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: flavorverse-api

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'flavorverse'
          slot-name: 'Production'
          publish-profile: ${{ secrets.__publishingprofilesecretname__ }}